/*
* Generated file
*
* Generated from: yang module name: office-service-impl yang module local name: office-service-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Aug 07 10:25:45 EDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.office_service.impl;
public class OfficeServiceModuleFactory extends org.opendaylight.controller.config.yang.config.office_service.impl.AbstractOfficeServiceModuleFactory {

}
